-- SH_MEMBER
DROP TABLE IF EXISTS "TRAN";

CREATE TABLE "TRAN"
(
    "NO"          BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    "NAME"        VARCHAR(128) NOT NULL,
    "CITY"        VARCHAR(32)  NOT NULL,
    "STORE_NAME"  VARCHAR(32) NOT NULL,
    "PRICE"       INT NOT NULL,
    "TRADE_DT"    TIMESTAMP NOT NULL,
    "STATE"       VARCHAR(16)  NOT NULL,
    "CREATOR"     VARCHAR(32) NOT NULL,
    "MODIFIER"    VARCHAR(32),
    "CREATED_DT"  TIMESTAMP NOT NULL,
    "MODIFIED_DT" TIMESTAMP,
    "IS_DELETED"  VARCHAR(1) NOT NULL
);